#!/bin/sh
#
# @name Gazebo adr_racer (250-class racing quad)
# @type Quadrotor
#
# 자동 생성: adr_sim/scripts/gen_racer_model.py (스펙: config/racer_spec.yaml). 직접 수정하지 말 것.
# 설치: adr_sim/scripts/install_px4_assets.sh 가 PX4 ROMFS airframes 에 링크·등록한다.

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=adr_cross}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=adr_racer}

param set-default SIM_GZ_EN 1

# ---- 제어 할당: x-config, 로터 위치(FRD) = 스펙 arm_length/√2 ----
param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.0883883
param set-default CA_ROTOR0_PY 0.0883883
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR1_PX -0.0883883
param set-default CA_ROTOR1_PY -0.0883883
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR2_PX 0.0883883
param set-default CA_ROTOR2_PY -0.0883883
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.0883883
param set-default CA_ROTOR3_PY 0.0883883
param set-default CA_ROTOR3_KM -0.05

# ---- gz 모터 명령(rad/s). MAX 는 model.sdf 의 maxRotVelocity 와 반드시 동일 ----
param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_MIN1 300
param set-default SIM_GZ_EC_MAX1 3000
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_MIN2 300
param set-default SIM_GZ_EC_MAX2 3000
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_MIN3 300
param set-default SIM_GZ_EC_MAX3 3000
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_MIN4 300
param set-default SIM_GZ_EC_MAX4 3000

# ---- 레이싱용 position controller 한계 ----
# 호버 추력(정규화): ω_hover = sqrt(mg/4/kf) 를 [EC_MIN, EC_MAX] 에 선형 매핑한 값
param set-default MPC_THR_HOVER 0.31
param set-default MPC_XY_VEL_MAX 10
param set-default MPC_Z_VEL_MAX_UP 5
param set-default MPC_Z_VEL_MAX_DN 3
param set-default MPC_ACC_HOR 8
param set-default MPC_ACC_UP_MAX 8
param set-default MPC_ACC_DOWN_MAX 6
param set-default MPC_JERK_AUTO 20
param set-default MPC_YAWRAUTO_MAX 200
param set-default MPC_TILTMAX_AIR 60
param set-default MC_PITCHRATE_MAX 800
param set-default MC_ROLLRATE_MAX 800
param set-default MC_YAWRATE_MAX 400

# 데이터링크 loss 시 hold (x500 과 동일)
param set-default NAV_DLL_ACT 2

param set-default EKF2_BCOEF_X 0.0
param set-default EKF2_BCOEF_Y 0.0
param set-default EKF2_MCOEF 0.12
